[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
# linker = "ld.musl-clang"
rustflags = [ "-C", "target-feature=+crt-static"]

[unstable]
# build-std = ["core", "compiler_builtins", "alloc", "std", "panic_abort"]